name: Build and Test Contracts

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ton-actions/setup-tools@v2

      - name: Build contracts
        run: |
          sed 's/STDLIB_PATH=stdlib_sol.tvm/STDLIB_PATH=${TVM_LINKER_LIB_PATH}/g' .env.dist > .env 
          make build
          make clean-tmp
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build-artifacts/
