name: Build and Test Contracts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      nodese:
        image: tonlabs/local-node
        ports:
          - 80:80
        env:
          USER_AGREEMENT: yes
    
    steps:
      - uses: actions/checkout@v2
      - uses: ton-actions/setup-tools@v2
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cache node modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependencies
        run: npm install
       
      - name: Build contracts
        run: |
          sed 's/STDLIB_PATH=stdlib_sol.tvm/STDLIB_PATH=${TVM_LINKER_LIB_PATH}/g' .env.dist > .env
          make build
      
      - name: Run magration to local node
        run: make deploy
      
      - name: Run tests
        run: make tests
      
      - name: Prepare files
        run: |
          make clean-tmp
          zip -r DeNS-contracts.zip ./build-artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: DeNS-contracts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
